### PR TITLE
[backport] modify test  

### PR DESCRIPTION
**Pull request by huoyue-git**
## What type of PR is this：
- [ ] bug
- [ ] feature
- [x] enhancement
- [ ] refactor
- [ ] others

## Which issues of this PR fixes ：

Fixes #

### CODE REVIEW

**Comment by dulong41** [comment]
run starrocks_admit_test

**Comment by dulong41** [comment]
run starrocks_admit_test

**Review by dulong41 — APPROVED** [review]

**Review by dulong41 — APPROVED** [review]

**Review by dulong41 — APPROVED** [review]

**Review by dulong41 — APPROVED** [review]

**Review by dulong41 — APPROVED** [review]

**Review by dulong41 — APPROVED** [review]

**Review by dulong41 — APPROVED** [review]

**Comment by dulong41** [comment]
run starrocks_admit_test

**Review by dulong41 — APPROVED** [review]

**Review by dulong41 — APPROVED** [review]

**Review by dulong41 — APPROVED** [review]

**Review by dulong41 — APPROVED** [review]

**Comment by dulong41** [comment]
run Trigger-Admit-Test

**Comment by dulong41** [comment]
run all

**Review by dulong41 — APPROVED** [review]

**Review by dulong41 — APPROVED** [review]

**Review by dulong41 — APPROVED** [review]

**Review by dulong41 — APPROVED** [review]

**Review by dulong41 — APPROVED** [review]

**Review by dulong41 — APPROVED** [review]

**Review by dulong41 — APPROVED** [review]

**Comment by dulong41** [comment]
run starrocks_admit_test

**Comment by dulong41** [comment]
run starrocks_admit_test

**Comment by dulong41** [comment]
run starrocks_admit_test

**Comment by dulong41** [comment]
run starrocks_admit_test

**Comment by dulong41** [comment]
run starrocks_admit_test

**Review by dulong41 — APPROVED** [review]

**Comment by dulong41** [comment]
run starrocks_admit_test

**Review by colorfulu — APPROVED** [review]

**Comment by dulong41** [comment]
run starrocks_admit_test

**Comment by dulong41** [comment]
run starrocks_admit_test

**Comment by dulong41** [comment]
run starrocks_admit_test

**Comment by dulong41** [comment]
run starrocks_admit_test

**Comment by dulong41** [comment]
run starrocks_admit_test

**Comment by dulong41** [comment]
run starrocks_admit_test

**Comment by dulong41** [comment]
run starrocks_admit_test

**Comment by dulong41** [comment]
run starrocks_admit_test

**Comment by dulong41** [comment]
run starrocks_admit_test

**Comment by dulong41** [comment]
run starrocks_admit_test

**Pull request closed without merging**
